jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use API Key
      run: echo ${{ secrets.API_KEY }}
      env:
        API_KEY: ${{ secrets.API_KEY }}
